CFLAGS = -std=c++11 -O3 -Wall

part1: part1.cpp
	g++ $(CFLAGS) part1.cpp -o part1 -lm

part2: part2.cpp
	g++ $(CFLAGS) part2.cpp -o part2 -lm

clean:
	rm -f *.o test

clean2:
	rm -f *.o

run:
	./test



